remote_theme: chrisrhymes/bulma-clean-theme/
show_downloads: true
title: Momento Clean
description: A minimal, clean and capable luancher.
permalink: pretty
fixed_navbar: top
defaults:
  -
  show_sidebar: false
  menubar: example_menu
